name: CI workflow

on: 
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Runnnign test
        run: echo "test are running"  # Install pytest

     